# Generated by Django 3.2 on 2021-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='scientific_name',
            field=models.CharField(default='edit this scientific name', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='IJSEM_list',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='etymology',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='domain',
            name='nomenclature_status',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='notes',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='proposed_as',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='domain',
            name='publication',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='domain',
            name='publication_status',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reference_list',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='taxonomic_status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
