# Generated by Django 3.2 on 2021-08-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0002_auto_20210811_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='scientific_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='scientific_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genus',
            name='scientific_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='scientific_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phylum',
            name='scientific_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
