# Generated by Django 3.2 on 2021-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0004_auto_20210823_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phylum',
            name='IJSEM_list',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='phylum',
            name='emendation',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='phylum',
            name='etymology',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='phylum',
            name='nomenclature_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='phylum',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='phylum',
            name='proposed_as',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='phylum',
            name='publication',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='phylum',
            name='taxonomic_status',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
