# Generated by Django 3.2 on 2021-08-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0005_auto_20210823_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='IJSEM_list',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='etymology',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='class',
            name='gender',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='class',
            name='nomenclature_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='proposed_as',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='publication',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='publication_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='taxonomic_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='IJSEM_list',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='etymology',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='family',
            name='gender',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='family',
            name='nomenclature_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='proposed_as',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='publication',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='publication_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='taxonomic_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='IJSEM_list',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='etymology',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='gender',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='nomenclature_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='proposed_as',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='publication',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='publication_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='reference_list',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='taxonomic_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='IJSEM_list',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etymology',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='order',
            name='nomenclature_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='proposed_as',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='publication',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='publication_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxonomic_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='IJSEM_list',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='basonym',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='etymology',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='gender',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='nomenclature_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='notes',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='proposed_as',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='publication',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='publication_status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='reference_list',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxonomic_status',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
