# Generated by Django 3.2 on 2021-08-23 10:45

import Taxonomy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0006_auto_20210823_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='rna_gene',
            field=models.FileField(max_length=256, null=True, upload_to=Taxonomy.models.get_upload_genus_path),
        ),
    ]
