# Generated by Django 3.2 on 2021-08-23 10:52

import Taxonomy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0007_alter_genus_rna_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='rna_gene',
            field=models.FileField(max_length=256, null=True, upload_to=Taxonomy.models.get_upload_species_path),
        ),
    ]
