# Generated by Django 3.2 on 2021-08-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0010_auto_20210826_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='IJSEM_list',
            field=models.CharField(default='none', max_length=1024),
        ),
        migrations.AlterField(
            model_name='domain',
            name='nomenclature_status',
            field=models.CharField(default='none', max_length=1024),
        ),
        migrations.AlterField(
            model_name='domain',
            name='notes',
            field=models.CharField(default='none', max_length=1024),
        ),
        migrations.AlterField(
            model_name='domain',
            name='publication_status',
            field=models.CharField(default='none', max_length=1024),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reference_list',
            field=models.JSONField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='taxonomic_status',
            field=models.CharField(default='none', max_length=1024),
        ),
    ]
