# Generated by Django 3.2 on 2021-09-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0011_auto_20210826_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='genus',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='phylum',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='name',
            new_name='category_name',
        ),
    ]
