# Generated by Django 3.2 on 2021-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='reference_list',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
