# Generated by Django 3.2 on 2021-05-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taxonomy', '0001_initial'),
        ('Strain', '0002_strain_reference_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taxonomy.class'),
        ),
        migrations.AddField(
            model_name='strain',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taxonomy.domain'),
        ),
        migrations.AddField(
            model_name='strain',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taxonomy.family'),
        ),
        migrations.AddField(
            model_name='strain',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taxonomy.genus'),
        ),
        migrations.AddField(
            model_name='strain',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taxonomy.order'),
        ),
        migrations.AddField(
            model_name='strain',
            name='phylum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taxonomy.phylum'),
        ),
        migrations.AddField(
            model_name='strain',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taxonomy.species'),
        ),
    ]
