# Generated by Django 3.2 on 2021-09-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strain', '0004_auto_20210823_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strain',
            old_name='name',
            new_name='strain_name',
        ),
    ]
