# Generated by Django 3.2 on 2021-11-04 07:33

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('landline_number', models.CharField(max_length=50)),
                ('address', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to=User.models.get_account_image_upload_path)),
                ('role', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
