# Generated by Django 3.2 on 2021-11-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='landline_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
