var categoryContents = {
  Domain: [
    ["Name", "category_name", "text"],
    ["Scientific Name", "scientific_name", "text"],
    ["Etymology", "etymology", "text"],
    ["Proposed As", "proposed_as", "text"],
    ["Publication", "publication", "textarea"],
    ["Publication Status", "publication_status", "text"],
    ["IJSEM List", "IJSEM_list", "textarea"],
    ["Notes", "notes", "textarea"],
    ["Nomenclature Status", "nomenclature_status", "text"],
    ["Taxonomic Status", "taxonomic_status", "text"],
  ],
  Phylum: [
    ["Name", "category_name", "text"],
    ["Scientific Name", "scientific_name", "text"],
    ["Etymology", "etymology", "text"],
    ["Proposed As", "proposed_as", "text"],
    ["Publication", "publication", "textarea"],
    ["Publication Status", "publication_status", "text"],
    ["IJSEM List", "IJSEM_list", "textarea"],
    ["Notes", "notes", "textarea"],
    ["Nomenclature Status", "nomenclature_status", "text"],
    ["Taxonomic Status", "taxonomic_status", "text"],
    ["Parent", "parent.category_name", "number"],
  ],
  Class: [
    ["Name", "category_name", "text"],
    ["Scientific Name", "scientific_name", "text"],
    ["Etymology", "etymology", "text"],
    ["Gender", "gender", "text"],
    ["Proposed As", "proposed_as", "text"],
    ["Publication", "publication", "textarea", "text"],
    ["Publication Status", "publication_status", "text", "text"],
    ["IJSEM List", "IJSEM_list", "textarea"],
    ["Notes", "notes", "textarea"],
    ["Nomenclature Status", "nomenclature_status", "text"],
    ["Taxonomic Status", "taxonomic_status", "text"],
    ["Parent", "parent.category_name", "number"],
  ],
  Order: [
    ["Name", "category_name", "text"],
    ["Scientific Name", "scientific_name", "text"],
    ["Etymology", "etymology", "text"],
    ["Gender", "gender", "text"],
    ["Proposed As", "proposed_as", "text"],
    ["Publication", "publication", "textarea", "text"],
    ["Publication Status", "publication_status", "text", "text"],
    ["IJSEM List", "IJSEM_list", "textarea"],
    ["Notes", "notes", "textarea"],
    ["Nomenclature Status", "nomenclature_status", "text"],
    ["Taxonomic Status", "taxonomic_status", "text"],
    ["Parent", "parent.category_name", "number"],
  ],
  Family: [
    ["Name", "category_name", "text"],
    ["Scientific Name", "scientific_name", "text"],
    ["Etymology", "etymology", "text"],
    ["Gender", "gender", "text"],
    ["Proposed As", "proposed_as", "text"],
    ["Publication", "publication", "textarea", "text"],
    ["Publication Status", "publication_status", "text", "text"],
    ["IJSEM List", "IJSEM_list", "textarea"],
    ["Notes", "notes", "textarea"],
    ["Nomenclature Status", "nomenclature_status", "text"],
    ["Taxonomic Status", "taxonomic_status", "text"],
    ["Parent", "parent.category_name", "number"],
  ],
  Genus: [
    ["Name", "category_name", "text"],
    ["Scientific Name", "scientific_name", "text"],
    ["Etymology", "etymology", "text"],
    ["Gender", "gender", "text"],
    ["Proposed As", "proposed_as", "text"],
    ["Publication", "publication", "textarea", "text"],
    ["Publication Status", "publication_status", "text", "text"],
    ["IJSEM List", "IJSEM_list", "textarea"],
    ["Notes", "notes", "textarea"],
    ["Nomenclature Status", "nomenclature_status", "text"],
    ["Taxonomic Status", "taxonomic_status", "text"],
    ["Parent", "parent.category_name", "number"],
    ["RNA Gene", "rna_gene", "file"],
  ],
  Species: [
    ["Name", "category_name", "text"],
    ["Scientific Name", "scientific_name", "text"],
    ["Etymology", "etymology", "text"],
    ["Gender", "gender", "text"],
    ["Basonym", "basonym", "text"],
    ["Proposed As", "proposed_as", "text"],
    ["Publication", "publication", "textarea", "text"],
    ["Publication Status", "publication_status", "text", "text"],
    ["IJSEM List", "IJSEM_list", "textarea"],
    ["Notes", "notes", "textarea"],
    ["Nomenclature Status", "nomenclature_status", "text"],
    ["Taxonomic Status", "taxonomic_status", "text"],
    ["Parent", "parent.category_name", "number"],
    ["RNA Gene", "rna_gene", "file"],
  ],
};

export { categoryContents };
